# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('membercard', models.CharField(max_length=20)),
                ('bookeddoctor', models.CharField(max_length=20)),
                ('bookeditem', models.CharField(max_length=50)),
                ('bookedtime', models.CharField(max_length=20)),
                ('webchatid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(default='001', max_length=6)),
                ('doctorname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=11)),
                ('comments', models.CharField(max_length=400)),
                ('service', models.CharField(max_length=200)),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vipno', models.CharField(max_length=11)),
                ('vipname', models.CharField(max_length=10)),
                ('vipnameid', models.CharField(max_length=18)),
                ('phonenumber', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('lastamount', models.FloatField()),
                ('discounttype', models.CharField(max_length=20)),
                ('discountrate', models.FloatField()),
                ('discountrate2', models.FloatField()),
                ('webchatid', models.CharField(max_length=50)),
                ('webchatid2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipAmountLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('addAmount', models.FloatField()),
                ('username', models.CharField(default='admin', max_length=10)),
                ('transactionDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messageId', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(max_length=2)),
                ('paymenttypename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratename', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('morningdiscount', models.FloatField()),
                ('commnets', models.CharField(max_length=50)),
                ('nextCardNo', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50)),
                ('servicerate', models.IntegerField()),
                ('serviceperiod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('doctorId', models.CharField(max_length=10)),
                ('bookingId', models.CharField(max_length=10)),
                ('servicetypeId', models.CharField(max_length=10)),
                ('productIds', models.CharField(default='', max_length=50)),
                ('account', models.IntegerField(default=1)),
                ('paymentType', models.CharField(max_length=2)),
                ('serviceamount', models.FloatField(default=0)),
                ('productamount', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=1)),
                ('successFlag', models.CharField(max_length=1)),
                ('transactionDate', models.DateField()),
                ('username', models.CharField(default='admin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorId', models.CharField(max_length=10)),
                ('doctorName', models.CharField(default='', max_length=20)),
                ('vacationDate', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=8)),
                ('endtime', models.CharField(max_length=8)),
                ('flag', models.CharField(max_length=1)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
