# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('membercard', models.CharField(max_length=20)),
                ('bookeddoctor', models.CharField(max_length=20)),
                ('bookeditem', models.CharField(max_length=50)),
                ('bookedtime', models.CharField(max_length=20)),
                ('webchatid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=11)),
                ('comments', models.CharField(max_length=400)),
                ('service', models.CharField(max_length=200)),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vipno', models.CharField(max_length=11)),
                ('vipname', models.CharField(max_length=10)),
                ('vipnameid', models.CharField(max_length=18)),
                ('phonenumber', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('lastamount', models.FloatField()),
                ('discounttype', models.CharField(max_length=20)),
                ('discountrate', models.FloatField()),
                ('discountrate2', models.FloatField()),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipAmountLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('addAmount', models.FloatField()),
                ('transactionDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratename', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('morningdiscount', models.FloatField()),
                ('commnets', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50)),
                ('servicerate', models.IntegerField()),
                ('serviceperiod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('doctorId', models.CharField(max_length=10)),
                ('bookingId', models.CharField(max_length=10)),
                ('servicetypeId', models.CharField(max_length=10)),
                ('paymentType', models.CharField(max_length=2)),
                ('amount', models.FloatField()),
                ('successFlag', models.CharField(max_length=1)),
                ('transactionDate', models.DateField()),
            ],
        ),
    ]
