# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('membercard', models.CharField(max_length=20)),
                ('bookeddoctor', models.CharField(max_length=20)),
                ('bookeditem', models.CharField(max_length=50)),
                ('bookedtime', models.CharField(max_length=20)),
                ('webchatid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=11)),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorid', models.IntegerField()),
                ('servicetypeid', models.IntegerField()),
                ('servicename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discounttype', models.CharField(max_length=20)),
                ('discountrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50)),
                ('servicerate', models.IntegerField()),
            ],
        ),
    ]
