# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='vipno',
            field=models.CharField(max_length=11),
        ),
    ]
