# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('membercard', models.CharField(max_length=20)),
                ('bookeddoctor', models.CharField(max_length=20)),
                ('bookeditem', models.CharField(max_length=50)),
                ('bookedtime', models.DateTimeField()),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=11)),
                ('webchatid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.IntegerField()),
                ('servicetypeid', models.IntegerField()),
                ('servicename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounttype', models.CharField(max_length=20)),
                ('discountrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=50)),
                ('servicerate', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='Pword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='Username',
            new_name='username',
        ),
    ]
