# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='lastamount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='password',
            field=models.CharField(default='000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='vipno',
            field=models.CharField(default='000001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='webchatid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
