# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttypeid', models.CharField(max_length=2)),
                ('paymenttype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(default='2', max_length=1),
            preserve_default=False,
        ),
    ]
