# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0002_auto_20160718_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='phonenumber',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='vipname',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
