# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0002_auto_20160629_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='status',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='bookedtime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorservicetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
