# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0002_auto_20160731_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='vipnameid',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
