# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0002_auto_20160910_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='paymenttypeid',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='paymenttypename',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='paymenttype',
            field=models.CharField(max_length=2),
        ),
    ]
