# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0002_auto_20170109_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='webchatid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='webchatid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='membership',
            name='webchatid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='membership',
            name='webchatid2',
            field=models.CharField(default='', max_length=128),
        ),
    ]
