# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0003_membership_vipnameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('doctorId', models.CharField(max_length=10)),
                ('servicetypeId', models.CharField(max_length=10)),
                ('paymentType', models.CharField(max_length=2)),
                ('amount', models.FloatField()),
                ('transactionDate', models.DateField()),
            ],
        ),
    ]
