# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0003_auto_20160910_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='productIds',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='productamount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='serviceamount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
