# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0003_auto_20170406_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='preamount',
            field=models.FloatField(default=0),
        ),
    ]
