# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='comments',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='service',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='discountrate2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
