# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0004_auto_20160917_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.FloatField(default=1),
        ),
    ]
