# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0005_auto_20160813_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratename', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorServiceType',
        ),
    ]
