# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0005_transaction_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorId', models.CharField(max_length=10)),
                ('vacationDate', models.DateField()),
                ('starttime', models.CharField(max_length=8)),
                ('endtime', models.CharField(max_length=8)),
                ('flag', models.CharField(max_length=1)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
