# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0006_auto_20160813_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipAmountLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membershipId', models.CharField(max_length=10)),
                ('addAmount', models.FloatField()),
                ('transactionDate', models.DateField()),
            ],
        ),
    ]
