# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0006_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacationDate',
            field=models.CharField(max_length=10),
        ),
    ]
