# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0006_auto_20180703_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ordertype',
            field=models.CharField(default='', max_length=1),
        ),
    ]
