# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0007_transaction_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='deleteAdminUser',
            field=models.CharField(default='', max_length=10),
        ),
    ]
