# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0007_membershipamountlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipamountlog',
            name='transactionDate',
            field=models.DateTimeField(),
        ),
    ]
