# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0007_auto_20160921_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='doctorName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
