# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0008_auto_20160823_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='successFlag',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
