# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0008_vacation_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='nextCardNo',
            field=models.FloatField(default=100000),
        ),
    ]
