# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0009_servicerate_nextcardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='nextCardNo',
            field=models.IntegerField(default=100000),
        ),
    ]
