# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0009_transaction_successflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bookingId',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
