# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0010_transaction_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='serviceperiod',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
