# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0010_auto_20160923_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='sn',
            field=models.CharField(default='001', max_length=6),
        ),
    ]
