# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0011_servicetype_serviceperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='commnets',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerate',
            name='morningdiscount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
