# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0011_doctorinfo_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
