# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0012_auto_20161016_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipamountlog',
            name='username',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
