# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0013_membershipamountlog_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messageId', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
