# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthModel', '0014_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='webchatid2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
